server:
  servlet:
    session:
      timeout: PT2H 

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    active: gao

  http:
    encoding:
      charset: UTF-8
      force: true
  #json日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#指定mapper文件的位置
mybatis:
  table:
    auto: update
  model:
    #扫描用于创建表的对象的包名
    pack: com.jlu.bookshop.entity
  database:
    type: mysql
  mapper-locations: classpath:mappers/*.xml,classpath:mappers/customize/*.xml

#mybatis-pageHelper分页工具
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql